# Generated by Django 2.2.4 on 2019-09-09 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('name', models.TextField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundboard.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundboard.Clip')),
                ('next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='soundboard.PlaylistClip')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundboard.Playlist')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='clips',
            field=models.ManyToManyField(through='soundboard.PlaylistClip', to='soundboard.Clip'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundboard.Clip')),
            ],
        ),
        migrations.AddConstraint(
            model_name='playlistclip',
            constraint=models.UniqueConstraint(fields=('playlist', 'clip'), name='unique_playlist_clip'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_user_playlist'),
        ),
        migrations.AddConstraint(
            model_name='clip',
            constraint=models.UniqueConstraint(fields=('name', 'board'), name='unique_board_clip'),
        ),
    ]
