# Generated by Django 3.0.4 on 2020-04-26 02:00

from django.db import migrations, models
import django.db.models.deletion
import soundboard.models
import soundboard.validators


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='cover',
            field=models.ImageField(default=1, upload_to=soundboard.models.board_upload_handler),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clip',
            name='sound',
            field=models.FileField(default=1, upload_to=soundboard.models.clip_upload_handler, validators=[soundboard.validators.FileTypeValidator(allowed_extensions=['audio/mpeg', 'audio/ogg'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clip',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='soundboard.Board'),
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('A', 'Admin'), ('M', 'Moderator'), ('B', 'Banned'), ('N', 'Normal')], default='N', max_length=15)),
                ('intro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='soundboard.Clip')),
            ],
        ),
    ]
