# Generated by Django 3.0.4 on 2020-10-15 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard', '0003_auto_20200628_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='volume',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
