# Generated by Django 3.1.3 on 2020-12-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard', '0004_clip_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
